### ISSUE TITLE
Assessment Results

### ISSUE THREAD

**Issue by damwhit** [jrsewell400/mod_0_skills#1]
@jrsewell400 nice work on this! You are officially `technical ready`! A couple pieces of feedback to keep in mind for moving forward:
* make sure to use either snake_case or camelCase, not both. The most important thing is to be consistent in using the same one.
* `folded` would probably be a better attribute name than `fold`. Why?

**Comment by jrsewell400** [comment]
@damwhit Hey David, thanks for the feedback!  I will keep the case structure in mind for the future.  Camel case seems quicker to type and it easy to read, but is there any advantage to using snake_case that I migh not be aware of?  Also, folded would make more sense than fold as it's more akin to the state of the chair with respect to being a chair.  I might've been thinking along the lines of "Do you want fold the chair? T/F", but I can see how "folded" would get us a little closer to the actual state of the chair.
